apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v1
      kind: Mapping
      name: {{ .Values.deployment_name }}_mapping
      ambassador_id: {{ .Values.ambassador.id }}
      prefix: /api/{{ .Values.microservice_name }}/
      rewrite: /{{ .Values.microservice_name }}/
      service: {{ .Values.deployment_name }}.{{ .Values.namespace }}:{{ .Values.service.externalPortHttp }}
      timeout_ms: 60000
  labels:
    app: {{ .Values.deployment_name }}
  name: {{ .Values.deployment_name }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.externalPortHttp }}
      protocol: TCP
      targetPort: {{ .Values.service.internalPortHttp }}
  selector:
    app: {{ .Values.deployment_name }}