apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: allemanifests.alle.org
  labels:
    name: allemanifest
spec:
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        spec:
          type: object
          required:
            - kind
            - apiVersion
          properties:
            kind:
              type: string
            apiVersion:
              type: string
            metadata:
              type: object
              properties:
                alle_version:
                  type: string
                manifest_name:
                  type: string

  group: alle.org
  versions:
    - name: v1
      served: true
      storage: true

  scope: Namespaced
  names:
    plural: allemanifests
    singular: allemanifest
    kind: AlleManifest
    shortNames:
      - am